name: "Changed files detection"
description: "Find the added and modified files due to a github event"
outputs:
  files:
    description: "Paths of all added or modified files"
    value: ${{ steps.changed-files.outputs.files }}
runs:
  using: "composite"
  steps:
    - name: "Get added and modified files"
      shell: bash
      id: changed-files
      run: |
        set -x

        PUSH_BASE_SHA=${{ github.event.before }}
        PR_BASE_SHA=${{ github.event.pull_request.base.sha }}

        if [ ! -z "$PR_BASE_SHA" ]; then
          CHANGED_FILES=`git log --no-merges --name-status --pretty=format: "$PR_BASE_SHA..HEAD" | grep -E "^M|^A" | awk '{print $2}'`
        elif [ ! -z "$PUSH_BASE_SHA" ]; then
          git fetch origin "$PUSH_BASE_SHA"
          CHANGED_FILES=`git diff --no-merges --name-status "$PUSH_BASE_SHA" HEAD | grep -E "^M|^A" | awk '{print $2}'`
        else
          echo "Only pull_request and push events are supported"
          exit 1
        fi

        echo "::set-output name=files::$CHANGED_FILES"

